### ISSUE TITLE
MenuKeyboard action shows a tiny black square in the middle of the screen.

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#713]
I hope this isn't just me again.

I updated to 3.0.7 and now when I select the MenuKeyboard action on my custom dynamic keyboard, I just get a tiny black square in the middle of the screen. There's no way to recover from this other than restarting OptiKey.

I just checked the wiki but didn't notice anything that might have changed.

Windows 7
Tobii 4C

I've been using floating keyboard setting instead of docked. Maybe that's related.

[FinnishKeyboard.txt](https://github.com/OptiKey/OptiKey/files/5178451/FinnishKeyboard.txt)

[user.config.txt](https://github.com/OptiKey/OptiKey/files/5177763/user.config.txt)

**Comment by lsaranto** [comment]
It appears, that the tiny black square is actually the menu screen/keyboard. It's just that it's been shrunk to 16x16 pixels in size. It is possible to resize the window by grabbing from the corner with the mouse. The window holds its new size until OptiKey is restarted. Then it goes back to that 16x16 size.

**Comment by JuliusSweetland** [comment]
@lsaranto Yes this is a problem we are actively looking into at the moment. A new version will be released with a fix as soon as possible! For now I would recommend downgrading to 3.0.5 if it is causing you major problems: https://github.com/OptiKey/OptiKey/releases/tag/v3.0.5

@AdamRoden @kmcnaught Another example of the sizing issue.

**Comment by JuliusSweetland** [comment]
@lsaranto There's a pre-release with a fix available here if you have a chance to test: https://github.com/OptiKey/OptiKey/releases/tag/v3.0.8_pre-release_3

**Comment by lsaranto** [comment]
Updated to 3.0.8. The issue is still present.

To clarify, my custom dynamic keyboard works fine. It's the built-in keyboard that comes up with MenuKeyboard action that is sized wrong. The one with keys for exit, minimize, sleep, default keyboards, etc.

I believe I was using 3.0.6 before 3.0.7 (I have a 3.0.6.0 folder under AppData\Roaming\OptiKey\OptikeyPro.exe_Url_<lettersandnumbers>). 3.0.6 worked ok. Maybe that helps to find the commit that broke it.

**Comment by JuliusSweetland** [comment]
@lsaranto Could you post (or email me at julius@optikey.org) the dynamic keyboard you are using and the exact steps to replicate?

@AdamRoden @kmcnaught Issue still present with 3.0.8, unfortunately. Any other ideas?

**Comment by JuliusSweetland** [comment]
@lsaranto Can you change your startup keyboard to a non-dynamic keyboard and test? We think it's related to the startup keyboard.

**Comment by AdamRoden** [comment]
@JuliusSweetland @lsaranto There was indeed an issue with using a dynamic keyboard as the startup keyboard. I added an additional check to handle the situation and am hoping Julius can do another pre-release soon.

**Comment by lsaranto** [comment]
Okay, new info.

Selected Letters as default keyboard. Restart OptiKey. The keyboard opens the same size (*) as I previously had resized the MenuKeyboard with the mouse. Open my keyboard from OptiKey (not Management Console), restart OptiKey. Again the startup keyboard is the size (*) I left it. As long as I have the startup keyboard set to a built-in keyboard, it remembers its size (*). After I go back to my dynamic keyboard as startup, and select MenuKeyboard action, the black square is back.

My dynamic keyboards all open with their intended sizes every time. I also tried the included sample dynamic keyboards, like AltAlphaHorizontalKeyboard. They open with the same size as the other built-in keyboards. What is their intended size, especially when Window state is set to Floating?

Note: the (*) is an attempt to better indicate what size I am referring to.

**Comment by lsaranto** [comment]
I played around a bit more. I changed the PersistNewState setting in my dynamic keyboard from False to True. Now all keyboards seem to follow this new size. So it is pretty much back how it used to be.

However, all this playing around with settings has messed up the icon/key that is shown when minimizing the keyboard. Now, for some reason, it's humongous! It's almost half of my screen. There used to be a setting in the Management Console for this, I think, but I can't find it anymore.

**Comment by JuliusSweetland** [comment]
From the code it looks like the minimised size is set using the full dock
thickness and the collapsed dock thickness. Can you check these values in
the Management Console and see if either have blown up?

**Comment by lsaranto** [comment]
After restart the icon is back to a reasonable size, but still bigger than what it was.

I was remembering that it was called something pretty clear. For whatever reason, I don't have either of those settings in the Management Console. Also, the Window state has become grayed out and I can no longer change it from Floating.

**Comment by JuliusSweetland** [comment]
In what state is Optikey when you are trying to change the Floating/Docked
state in the Management Console? If it is Maximised or Minimised this
options is not available. It may also not be available if the current
window does not have a persisted state, e.g. a dynamic keyboard.

**Comment by lsaranto** [comment]
Okay, wouldn't have thought that. So when I have Letters as keyboard, I can change the Window state. 

I also found the appropriate setting in user.config file and changed it there.

**Comment by lsaranto** [comment]
It's the PersistNewState = True that causes the humongous minimized icon.

**Comment by JuliusSweetland** [comment]
Can you give me some more details on what you mean?

**Comment by lsaranto** [comment]
About the minimized icon size?
Okay, so earlier I noticed that setting PersistNewState to True in my dynamic keyboard file would make the built-in keyboards behave properly(-ish). After the humongous icon appeared, I had apparently changed PersistNewState back to False. Now I tried PNS = True, again. And lo and behold, the humongous icon is back.

Looks like it changes MainWindowCollapsedDockThicknessAsPercentageOfFullDockThickness to 100 in user.config I normally have it at 10. As long as PNS is True, there's no point in trying to edit it manually. It gets changed back when OptiKey restarts.

**Comment by JuliusSweetland** [comment]
Right, understood. That's something we are trying to fix are the moment.
Thanks

**Comment by kmcnaught** [comment]
My PR should fix the initial problem. The later issues described might be complicated by the fact that the first problem was causing the tiny square to be saved as the 'normal' Optikey size. If you later loaded a floating keyboard with PersistNewState=true then this will have overridden the saved size and position. 

It does sound like you might have found a problem with the minimised size, but the details are complicated by interactions with the previous bug. 

When Julius has made a prerelease available with the latest fix, it would be useful to start from a working state and again give us some instructions for how to replicate the problem, ideally with a sample keyboard too.

**Comment by JuliusSweetland** [comment]
@lsaranto Could you please try the latest pre-release of 3.0.8 here: https://github.com/OptiKey/OptiKey/releases/tag/v3.0.8_pre-release_4

FYI you may have to resize manually (or factory reset your Optikey settings) to be able to test cleanly.

**Comment by JuliusSweetland** [comment]
@lsaranto Full release of 3.0.8 has gone out.

I'll close this issue, but if the problem still occurs please open a new issue and we can continue from that.
