### ISSUE TITLE
Option to disable "Uh-oh" message

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#780]
When using the keyboard key trigger mechanism, if the key is pressed while the gaze is not detected, OptiKey generates a large red "Uh-oh!" message suggesting that the user check that their pointing device is plugged in, turned on, calibrated, etc. (I assume that the same message appears when using the mouse click trigger mechanism.)

As someone who uses the keyboard key trigger mechanism (by means of external switches that emulate keyboard keypresses), I see this message quite a bit. Sometimes I just bump one of my switches while not even looking at the screen. Sometimes the eye tracker just loses my gaze for a moment. 

In either case, it's annoying. It disrupts the flow of my work. And it's especially bad if it happens while I'm screen sharing on a Teams call. I have had coworkers get legitimately a bit freaked out thinking that something was wrong.

I absolutely understand the utility of this message for new users who may not understand why OptiKey isn't working.

As an advanced user, though, I would like the option to disable this message and the accompanying audio. 

If I'm not seeing the orange highlights on the keyboard, then I know that OptiKey isn't detecting my eyes and I need to address that. I don't need the error message.

**Comment by kmcnaught** [comment]
@JuliusSweetland is this best solved with just a feature toggle to turn off the current behaviour, or should we down-play the existing warnings so they are more helpful to beginners (e.g. don't show toast more than a certain number of times, and/or wait until several consecutive failed attempts)

**Comment by kmcnaught** [comment]
(those aren't mutually exclusive - the latter approach could trivially still have an option to be turned off completely)

**Comment by annakirkpatrick** [comment]
@kmcnaught just a few thoughts regarding your suggestions. It doesn't resolve the issue I'm having, but I can absolutely see value in, say, not showing up more than three error messages of this type in a five minute block of time. This would solve the pretty common issue where user (or helper) is fumbling around trying to set up or position a switch and the switch may be activated dozens of times within just a couple minutes. (I do sometimes run into this when I am setting up switches. I don't personally care about error messages in this context, but I can see how they could be annoying.)

For my use case, I do see more value in the second suggestion. For example, maybe you would only show the error after three consecutive switch presses without the gaze being detected. This would solve the issue sometimes created when the eye tracker just momentarily loses the gaze point.

Personally, I would still prefer to just be able to turn off the errors. But I do think a gentler error scheme could be nice for new users.

**Comment by kmcnaught** [comment]
I've added @annakirkpatrick 's request pending @JuliusSweetland's approval. This is also a repeat complaint by another switch user I'm working with! 

I think there is still an issue to be discussed, in that this seems to occur more often than feels natural. From the perspective of a user, a momentary lapse in gaze input shouldn't prevent the deliberate action of a trigger from being executed at the last known gaze point (which is visually signified with a highlight or mouse cursor). I know that elsewhere in the code there's the idea of a point's lifetime ("time to live") - but I'm not sure if it's relevant/being used here. 

I haven't had time to look into the sequence logic more closely to see if there's an easy way to make this more forgiving, perhaps @JuliusSweetland has more of an idea?

**Comment by annakirkpatrick** [comment]
@kmcnaught I want to add a little new nuance to your statement:

> From the perspective of a user, a momentary lapse in gaze input shouldn't prevent the deliberate action of a trigger from being executed at the last known gaze point (which is visually signified with a highlight or mouse cursor).

I frequently exceed 20 words a minute when typing with Optikey and a switch (without any word prediction).  20 words a minute is 100 characters a minute, which means I'm likely hitting two characters per second in the faster parts of my typing. My point is that my eyes are moving quite quickly, and we should be careful with what a "momentary lapse" actually means.

If, for example, you allowed for 0.5 second lapse and still interpreted the switch press to mean the last known gaze point, that could easily lead to erroneous input for a fast gaze typist.  I would think much shorter lapses (e.g. 100 ms) would be good candidates for filling in with the last known gaze point.

If you write some code to do this (or it turns out that this code already exists), I would be happy to do some testing with different time intervals to see at what point I start getting erroneous input.

**Comment by JuliusSweetland** [comment]
@kmcnaught It feels like using the last known point (with TTL) could be problematic. I think the easiest way forward would be to add a new setting to downgrade the current toast error to just a warning sound.

@annakirkpatrick Would this get you close enough to the behaviour that you want? Optikey would be a lot less annoying if you didn't have to wait for the toast and the notification sound was more subtle.

**Comment by kmcnaught** [comment]
@annakirkpatrick @JuliusSweetland I take your point. I certainly wasn't imagining a 0.5 second lapse, it just felt to me like what was happeningin practise was that points were coming in at 30-60 FPS but sometimes missing a single data point, i.e. a lapse around 50-100ms. Since you do get a visual indicator of gaze position (as the key is highlighted) I imagined the UX would be that as soon as you have seen that the correct letter is selected, you press your switch and it forgives a single missing data point while you're pressing your switch. 

I'll certainly defer to an every day user though! I'm not sure how easy it would be to add separate (much-smaller) TTL logic for the switch triggers. If @JuliusSweetland can suggest a snazzy LINQ sequence one-liner or similar then I'd say it could be worth a try, otherwise ignore my suggestion.

**Comment by annakirkpatrick** [comment]
@kmcnaught The behavior I see when using OptiKey suggests that it's probably already a little forgiving in terms of missing a single data point.  Not sure, but I wonder if this is already done.  (Either in OptiKey or perhaps in Tobii's software.)

Actually, the fact that smoothing is used suggests it probably is done.  If you're averaging (in a complicated way, granted) recent measurements, that gives an easy way to fill in a single missing point.

@JuliusSweetland I agree to changing to a gentler warning sound and removing the toast error banner would be a totally acceptable solution.  (And the fact that the user can select sounds in OptiKey would, I think, mean that the warning could be completely removed to selecting a "blank" sound for that warning.)
